/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MembergroupService } from "../membergroup.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MembergroupCreateInput } from "./MembergroupCreateInput";
import { MembergroupWhereInput } from "./MembergroupWhereInput";
import { MembergroupWhereUniqueInput } from "./MembergroupWhereUniqueInput";
import { MembergroupFindManyArgs } from "./MembergroupFindManyArgs";
import { MembergroupUpdateInput } from "./MembergroupUpdateInput";
import { Membergroup } from "./Membergroup";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MembergroupControllerBase {
  constructor(
    protected readonly service: MembergroupService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Membergroup",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Membergroup })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: MembergroupCreateInput
  ): Promise<Membergroup> {
    return await this.service.create({
      data: {
        ...data,

        groupid: data.groupid
          ? {
              connect: data.groupid,
            }
          : undefined,

        memberid: data.memberid
          ? {
              connect: data.memberid,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        groupid: {
          select: {
            id: true,
          },
        },

        id: true,

        memberid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Membergroup",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Membergroup] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(MembergroupFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Membergroup[]> {
    const args = plainToClass(MembergroupFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,

        groupid: {
          select: {
            id: true,
          },
        },

        id: true,

        memberid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Membergroup",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Membergroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: MembergroupWhereUniqueInput
  ): Promise<Membergroup | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,

        groupid: {
          select: {
            id: true,
          },
        },

        id: true,

        memberid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Membergroup",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Membergroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: MembergroupWhereUniqueInput,
    @common.Body() data: MembergroupUpdateInput
  ): Promise<Membergroup | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          groupid: data.groupid
            ? {
                connect: data.groupid,
              }
            : undefined,

          memberid: data.memberid
            ? {
                connect: data.memberid,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          groupid: {
            select: {
              id: true,
            },
          },

          id: true,

          memberid: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Membergroup",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Membergroup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: MembergroupWhereUniqueInput
  ): Promise<Membergroup | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,

          groupid: {
            select: {
              id: true,
            },
          },

          id: true,

          memberid: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
