/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MyidentityService } from "../myidentity.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MyidentityCreateInput } from "./MyidentityCreateInput";
import { MyidentityWhereInput } from "./MyidentityWhereInput";
import { MyidentityWhereUniqueInput } from "./MyidentityWhereUniqueInput";
import { MyidentityFindManyArgs } from "./MyidentityFindManyArgs";
import { MyidentityUpdateInput } from "./MyidentityUpdateInput";
import { Myidentity } from "./Myidentity";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MyidentityControllerBase {
  constructor(
    protected readonly service: MyidentityService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Myidentity",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Myidentity })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: MyidentityCreateInput
  ): Promise<Myidentity> {
    return await this.service.create({
      data: {
        ...data,

        identityid: data.identityid
          ? {
              connect: data.identityid,
            }
          : undefined,

        myidentitycontactid: data.myidentitycontactid
          ? {
              connect: data.myidentitycontactid,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        identityid: {
          select: {
            id: true,
          },
        },

        myidentitycontactid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Myidentity",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Myidentity] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(MyidentityFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Myidentity[]> {
    const args = plainToClass(MyidentityFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,

        identityid: {
          select: {
            id: true,
          },
        },

        myidentitycontactid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Myidentity",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Myidentity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: MyidentityWhereUniqueInput
  ): Promise<Myidentity | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,

        identityid: {
          select: {
            id: true,
          },
        },

        myidentitycontactid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Myidentity",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Myidentity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: MyidentityWhereUniqueInput,
    @common.Body() data: MyidentityUpdateInput
  ): Promise<Myidentity | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          identityid: data.identityid
            ? {
                connect: data.identityid,
              }
            : undefined,

          myidentitycontactid: data.myidentitycontactid
            ? {
                connect: data.myidentitycontactid,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          identityid: {
            select: {
              id: true,
            },
          },

          myidentitycontactid: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Myidentity",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Myidentity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: MyidentityWhereUniqueInput
  ): Promise<Myidentity | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,

          identityid: {
            select: {
              id: true,
            },
          },

          myidentitycontactid: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
