/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { DatarequestUpdateManyWithoutCategoriesInput } from "./DatarequestUpdateManyWithoutCategoriesInput";
import { Type } from "class-transformer";
import { DatasuggestionUpdateManyWithoutCategoriesInput } from "./DatasuggestionUpdateManyWithoutCategoriesInput";
import { FileprofileUpdateManyWithoutCategoriesInput } from "./FileprofileUpdateManyWithoutCategoriesInput";
import { LinkcategoryUpdateManyWithoutCategoriesInput } from "./LinkcategoryUpdateManyWithoutCategoriesInput";
import { LinkprofileUpdateManyWithoutCategoriesInput } from "./LinkprofileUpdateManyWithoutCategoriesInput";
import { ProfileviewUpdateManyWithoutCategoriesInput } from "./ProfileviewUpdateManyWithoutCategoriesInput";
import { TemplatecategoryUpdateManyWithoutCategoriesInput } from "./TemplatecategoryUpdateManyWithoutCategoriesInput";
@InputType()
class CategoryUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  categoryname?: string | null;

  @ApiProperty({
    required: false,
    type: () => DatarequestUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => DatarequestUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => DatarequestUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  datarequests?: DatarequestUpdateManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => DatasuggestionUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => DatasuggestionUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => DatasuggestionUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  datasuggestions?: DatasuggestionUpdateManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => FileprofileUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => FileprofileUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => FileprofileUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  fileprofiles?: FileprofileUpdateManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => LinkcategoryUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => LinkcategoryUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => LinkcategoryUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  linkcategories?: LinkcategoryUpdateManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => LinkprofileUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => LinkprofileUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => LinkprofileUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  linkprofiles?: LinkprofileUpdateManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => ProfileviewUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => ProfileviewUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => ProfileviewUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  profileviews?: ProfileviewUpdateManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => TemplatecategoryUpdateManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => TemplatecategoryUpdateManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => TemplatecategoryUpdateManyWithoutCategoriesInput, {
    nullable: true,
  })
  templatecategories?: TemplatecategoryUpdateManyWithoutCategoriesInput;
}
export { CategoryUpdateInput };
