/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { DatarequestCreateNestedManyWithoutCategoriesInput } from "./DatarequestCreateNestedManyWithoutCategoriesInput";
import { Type } from "class-transformer";
import { DatasuggestionCreateNestedManyWithoutCategoriesInput } from "./DatasuggestionCreateNestedManyWithoutCategoriesInput";
import { FileprofileCreateNestedManyWithoutCategoriesInput } from "./FileprofileCreateNestedManyWithoutCategoriesInput";
import { LinkcategoryCreateNestedManyWithoutCategoriesInput } from "./LinkcategoryCreateNestedManyWithoutCategoriesInput";
import { LinkprofileCreateNestedManyWithoutCategoriesInput } from "./LinkprofileCreateNestedManyWithoutCategoriesInput";
import { ProfileviewCreateNestedManyWithoutCategoriesInput } from "./ProfileviewCreateNestedManyWithoutCategoriesInput";
import { TemplatecategoryCreateNestedManyWithoutCategoriesInput } from "./TemplatecategoryCreateNestedManyWithoutCategoriesInput";
@InputType()
class CategoryCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  categoryname?: string | null;

  @ApiProperty({
    required: false,
    type: () => DatarequestCreateNestedManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => DatarequestCreateNestedManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => DatarequestCreateNestedManyWithoutCategoriesInput, {
    nullable: true,
  })
  datarequests?: DatarequestCreateNestedManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => DatasuggestionCreateNestedManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => DatasuggestionCreateNestedManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => DatasuggestionCreateNestedManyWithoutCategoriesInput, {
    nullable: true,
  })
  datasuggestions?: DatasuggestionCreateNestedManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => FileprofileCreateNestedManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => FileprofileCreateNestedManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => FileprofileCreateNestedManyWithoutCategoriesInput, {
    nullable: true,
  })
  fileprofiles?: FileprofileCreateNestedManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => LinkcategoryCreateNestedManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => LinkcategoryCreateNestedManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => LinkcategoryCreateNestedManyWithoutCategoriesInput, {
    nullable: true,
  })
  linkcategories?: LinkcategoryCreateNestedManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => LinkprofileCreateNestedManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => LinkprofileCreateNestedManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => LinkprofileCreateNestedManyWithoutCategoriesInput, {
    nullable: true,
  })
  linkprofiles?: LinkprofileCreateNestedManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => ProfileviewCreateNestedManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => ProfileviewCreateNestedManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => ProfileviewCreateNestedManyWithoutCategoriesInput, {
    nullable: true,
  })
  profileviews?: ProfileviewCreateNestedManyWithoutCategoriesInput;

  @ApiProperty({
    required: false,
    type: () => TemplatecategoryCreateNestedManyWithoutCategoriesInput,
  })
  @ValidateNested()
  @Type(() => TemplatecategoryCreateNestedManyWithoutCategoriesInput)
  @IsOptional()
  @Field(() => TemplatecategoryCreateNestedManyWithoutCategoriesInput, {
    nullable: true,
  })
  templatecategories?: TemplatecategoryCreateNestedManyWithoutCategoriesInput;
}
export { CategoryCreateInput };
