import { Datarequest } from "../datarequest/Datarequest";
import { Datasuggestion } from "../datasuggestion/Datasuggestion";
import { Group } from "../group/Group";
import { Enumblockuser } from "../enumblockuser/Enumblockuser";
import { Linksharing } from "../linksharing/Linksharing";
import { Membergroup } from "../membergroup/Membergroup";
import { Myidentity } from "../myidentity/Myidentity";
import { Profile } from "../profile/Profile";
import { Profileview } from "../profileview/Profileview";

export type User = {
  apartment: string | null;
  city: string | null;
  country: string | null;
  createdAt: Date;
  datarequestsaskid?: Array<Datarequest>;
  datarequestsreceiveid?: Array<Datarequest>;
  datasuggestionsreceiveid?: Array<Datasuggestion>;
  datasuggestionssuggestionid?: Array<Datasuggestion>;
  email: string | null;
  firstName: string | null;
  groupsownerid?: Array<Group>;
  housnumber: string | null;
  id: string;
  image: string | null;
  isactive: boolean | null;
  isblocked?: Enumblockuser | null;
  isregistered: boolean | null;
  lastName: string | null;
  linksharings?: Array<Linksharing>;
  membergroups?: Array<Membergroup>;
  myidentitiesidentityid?: Array<Myidentity>;
  myidentitiesmyidentitycontactid?: Array<Myidentity>;
  phone: string | null;
  profiles?: Array<Profile>;
  profileviewsidentityid?: Array<Profileview>;
  profileviewswatchid?: Array<Profileview>;
  roles: Array<string>;
  street: string | null;
  updatedAt: Date;
  username: string;
};
