import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DatarequestListRelationFilter } from "../datarequest/DatarequestListRelationFilter";
import { DatasuggestionListRelationFilter } from "../datasuggestion/DatasuggestionListRelationFilter";
import { GroupListRelationFilter } from "../group/GroupListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { EnumblockuserWhereUniqueInput } from "../enumblockuser/EnumblockuserWhereUniqueInput";
import { LinksharingListRelationFilter } from "../linksharing/LinksharingListRelationFilter";
import { MembergroupListRelationFilter } from "../membergroup/MembergroupListRelationFilter";
import { MyidentityListRelationFilter } from "../myidentity/MyidentityListRelationFilter";
import { ProfileListRelationFilter } from "../profile/ProfileListRelationFilter";
import { ProfileviewListRelationFilter } from "../profileview/ProfileviewListRelationFilter";

export type UserWhereInput = {
  apartment?: StringNullableFilter;
  city?: StringNullableFilter;
  country?: StringNullableFilter;
  datarequestsaskid?: DatarequestListRelationFilter;
  datarequestsreceiveid?: DatarequestListRelationFilter;
  datasuggestionsreceiveid?: DatasuggestionListRelationFilter;
  datasuggestionssuggestionid?: DatasuggestionListRelationFilter;
  email?: StringNullableFilter;
  firstName?: StringNullableFilter;
  groupsownerid?: GroupListRelationFilter;
  housnumber?: StringNullableFilter;
  id?: StringFilter;
  image?: StringNullableFilter;
  isactive?: BooleanNullableFilter;
  isblocked?: EnumblockuserWhereUniqueInput;
  isregistered?: BooleanNullableFilter;
  lastName?: StringNullableFilter;
  linksharings?: LinksharingListRelationFilter;
  membergroups?: MembergroupListRelationFilter;
  myidentitiesidentityid?: MyidentityListRelationFilter;
  myidentitiesmyidentitycontactid?: MyidentityListRelationFilter;
  phone?: StringNullableFilter;
  profiles?: ProfileListRelationFilter;
  profileviewsidentityid?: ProfileviewListRelationFilter;
  profileviewswatchid?: ProfileviewListRelationFilter;
  street?: StringNullableFilter;
  username?: StringFilter;
};
