import { DatarequestUpdateManyWithoutUsersInput } from "./DatarequestUpdateManyWithoutUsersInput";
import { DatasuggestionUpdateManyWithoutUsersInput } from "./DatasuggestionUpdateManyWithoutUsersInput";
import { GroupUpdateManyWithoutUsersInput } from "./GroupUpdateManyWithoutUsersInput";
import { EnumblockuserWhereUniqueInput } from "../enumblockuser/EnumblockuserWhereUniqueInput";
import { LinksharingUpdateManyWithoutUsersInput } from "./LinksharingUpdateManyWithoutUsersInput";
import { MembergroupUpdateManyWithoutUsersInput } from "./MembergroupUpdateManyWithoutUsersInput";
import { MyidentityUpdateManyWithoutUsersInput } from "./MyidentityUpdateManyWithoutUsersInput";
import { ProfileUpdateManyWithoutUsersInput } from "./ProfileUpdateManyWithoutUsersInput";
import { ProfileviewUpdateManyWithoutUsersInput } from "./ProfileviewUpdateManyWithoutUsersInput";

export type UserUpdateInput = {
  apartment?: string | null;
  city?: string | null;
  country?: string | null;
  datarequestsaskid?: DatarequestUpdateManyWithoutUsersInput;
  datarequestsreceiveid?: DatarequestUpdateManyWithoutUsersInput;
  datasuggestionsreceiveid?: DatasuggestionUpdateManyWithoutUsersInput;
  datasuggestionssuggestionid?: DatasuggestionUpdateManyWithoutUsersInput;
  email?: string | null;
  firstName?: string | null;
  groupsownerid?: GroupUpdateManyWithoutUsersInput;
  housnumber?: string | null;
  image?: string | null;
  isactive?: boolean | null;
  isblocked?: EnumblockuserWhereUniqueInput | null;
  isregistered?: boolean | null;
  lastName?: string | null;
  linksharings?: LinksharingUpdateManyWithoutUsersInput;
  membergroups?: MembergroupUpdateManyWithoutUsersInput;
  myidentitiesidentityid?: MyidentityUpdateManyWithoutUsersInput;
  myidentitiesmyidentitycontactid?: MyidentityUpdateManyWithoutUsersInput;
  password?: string;
  phone?: string | null;
  profiles?: ProfileUpdateManyWithoutUsersInput;
  profileviewsidentityid?: ProfileviewUpdateManyWithoutUsersInput;
  profileviewswatchid?: ProfileviewUpdateManyWithoutUsersInput;
  roles?: Array<string>;
  street?: string | null;
  username?: string;
};
