import { DatarequestCreateNestedManyWithoutUsersInput } from "./DatarequestCreateNestedManyWithoutUsersInput";
import { DatasuggestionCreateNestedManyWithoutUsersInput } from "./DatasuggestionCreateNestedManyWithoutUsersInput";
import { GroupCreateNestedManyWithoutUsersInput } from "./GroupCreateNestedManyWithoutUsersInput";
import { EnumblockuserWhereUniqueInput } from "../enumblockuser/EnumblockuserWhereUniqueInput";
import { LinksharingCreateNestedManyWithoutUsersInput } from "./LinksharingCreateNestedManyWithoutUsersInput";
import { MembergroupCreateNestedManyWithoutUsersInput } from "./MembergroupCreateNestedManyWithoutUsersInput";
import { MyidentityCreateNestedManyWithoutUsersInput } from "./MyidentityCreateNestedManyWithoutUsersInput";
import { ProfileCreateNestedManyWithoutUsersInput } from "./ProfileCreateNestedManyWithoutUsersInput";
import { ProfileviewCreateNestedManyWithoutUsersInput } from "./ProfileviewCreateNestedManyWithoutUsersInput";

export type UserCreateInput = {
  apartment?: string | null;
  city?: string | null;
  country?: string | null;
  datarequestsaskid?: DatarequestCreateNestedManyWithoutUsersInput;
  datarequestsreceiveid?: DatarequestCreateNestedManyWithoutUsersInput;
  datasuggestionsreceiveid?: DatasuggestionCreateNestedManyWithoutUsersInput;
  datasuggestionssuggestionid?: DatasuggestionCreateNestedManyWithoutUsersInput;
  email?: string | null;
  firstName?: string | null;
  groupsownerid?: GroupCreateNestedManyWithoutUsersInput;
  housnumber?: string | null;
  image?: string | null;
  isactive?: boolean | null;
  isblocked?: EnumblockuserWhereUniqueInput | null;
  isregistered?: boolean | null;
  lastName?: string | null;
  linksharings?: LinksharingCreateNestedManyWithoutUsersInput;
  membergroups?: MembergroupCreateNestedManyWithoutUsersInput;
  myidentitiesidentityid?: MyidentityCreateNestedManyWithoutUsersInput;
  myidentitiesmyidentitycontactid?: MyidentityCreateNestedManyWithoutUsersInput;
  password: string;
  phone?: string | null;
  profiles?: ProfileCreateNestedManyWithoutUsersInput;
  profileviewsidentityid?: ProfileviewCreateNestedManyWithoutUsersInput;
  profileviewswatchid?: ProfileviewCreateNestedManyWithoutUsersInput;
  roles: Array<string>;
  street?: string | null;
  username: string;
};
