/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { LinksharingService } from "../linksharing.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LinksharingCreateInput } from "./LinksharingCreateInput";
import { LinksharingWhereInput } from "./LinksharingWhereInput";
import { LinksharingWhereUniqueInput } from "./LinksharingWhereUniqueInput";
import { LinksharingFindManyArgs } from "./LinksharingFindManyArgs";
import { LinksharingUpdateInput } from "./LinksharingUpdateInput";
import { Linksharing } from "./Linksharing";
import { LinkcategoryFindManyArgs } from "../../linkcategory/base/LinkcategoryFindManyArgs";
import { Linkcategory } from "../../linkcategory/base/Linkcategory";
import { LinkcategoryWhereUniqueInput } from "../../linkcategory/base/LinkcategoryWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LinksharingControllerBase {
  constructor(
    protected readonly service: LinksharingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Linksharing",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Linksharing })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: LinksharingCreateInput
  ): Promise<Linksharing> {
    return await this.service.create({
      data: {
        ...data,

        sharingid: data.sharingid
          ? {
              connect: data.sharingid,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        expiration: true,
        id: true,
        link: true,

        sharingid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Linksharing",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Linksharing] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(LinksharingFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Linksharing[]> {
    const args = plainToClass(LinksharingFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        expiration: true,
        id: true,
        link: true,

        sharingid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Linksharing",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Linksharing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: LinksharingWhereUniqueInput
  ): Promise<Linksharing | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        expiration: true,
        id: true,
        link: true,

        sharingid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Linksharing",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Linksharing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: LinksharingWhereUniqueInput,
    @common.Body() data: LinksharingUpdateInput
  ): Promise<Linksharing | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          sharingid: data.sharingid
            ? {
                connect: data.sharingid,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          expiration: true,
          id: true,
          link: true,

          sharingid: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Linksharing",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Linksharing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: LinksharingWhereUniqueInput
  ): Promise<Linksharing | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          expiration: true,
          id: true,
          link: true,

          sharingid: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Linkcategory",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/linkcategories")
  @ApiNestedQuery(LinkcategoryFindManyArgs)
  async findManyLinkcategories(
    @common.Req() request: Request,
    @common.Param() params: LinksharingWhereUniqueInput
  ): Promise<Linkcategory[]> {
    const query = plainToClass(LinkcategoryFindManyArgs, request.query);
    const results = await this.service.findLinkcategories(params.id, {
      ...query,
      select: {
        categoryid: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        linkid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Linksharing",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/linkcategories")
  async connectLinkcategories(
    @common.Param() params: LinksharingWhereUniqueInput,
    @common.Body() body: LinkcategoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      linkcategories: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Linksharing",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/linkcategories")
  async updateLinkcategories(
    @common.Param() params: LinksharingWhereUniqueInput,
    @common.Body() body: LinkcategoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      linkcategories: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Linksharing",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/linkcategories")
  async disconnectLinkcategories(
    @common.Param() params: LinksharingWhereUniqueInput,
    @common.Body() body: LinkcategoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      linkcategories: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
