/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateUserArgs } from "./CreateUserArgs";
import { UpdateUserArgs } from "./UpdateUserArgs";
import { DeleteUserArgs } from "./DeleteUserArgs";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserFindUniqueArgs } from "./UserFindUniqueArgs";
import { User } from "./User";
import { DatarequestFindManyArgs } from "../../datarequest/base/DatarequestFindManyArgs";
import { Datarequest } from "../../datarequest/base/Datarequest";
import { DatasuggestionFindManyArgs } from "../../datasuggestion/base/DatasuggestionFindManyArgs";
import { Datasuggestion } from "../../datasuggestion/base/Datasuggestion";
import { GroupFindManyArgs } from "../../group/base/GroupFindManyArgs";
import { Group } from "../../group/base/Group";
import { LinksharingFindManyArgs } from "../../linksharing/base/LinksharingFindManyArgs";
import { Linksharing } from "../../linksharing/base/Linksharing";
import { MembergroupFindManyArgs } from "../../membergroup/base/MembergroupFindManyArgs";
import { Membergroup } from "../../membergroup/base/Membergroup";
import { MyidentityFindManyArgs } from "../../myidentity/base/MyidentityFindManyArgs";
import { Myidentity } from "../../myidentity/base/Myidentity";
import { ProfileFindManyArgs } from "../../profile/base/ProfileFindManyArgs";
import { Profile } from "../../profile/base/Profile";
import { ProfileviewFindManyArgs } from "../../profileview/base/ProfileviewFindManyArgs";
import { Profileview } from "../../profileview/base/Profileview";
import { Enumblockuser } from "../../enumblockuser/base/Enumblockuser";
import { UserService } from "../user.service";

@graphql.Resolver(() => User)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class UserResolverBase {
  constructor(
    protected readonly service: UserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async _usersMeta(
    @graphql.Args() args: UserFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [User])
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async users(@graphql.Args() args: UserFindManyArgs): Promise<User[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "own",
  })
  async user(@graphql.Args() args: UserFindUniqueArgs): Promise<User | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => User)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "create",
    possession: "any",
  })
  async createUser(@graphql.Args() args: CreateUserArgs): Promise<User> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        isblocked: args.data.isblocked
          ? {
              connect: args.data.isblocked,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => User)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  async updateUser(@graphql.Args() args: UpdateUserArgs): Promise<User | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          isblocked: args.data.isblocked
            ? {
                connect: args.data.isblocked,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => User)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "delete",
    possession: "any",
  })
  async deleteUser(@graphql.Args() args: DeleteUserArgs): Promise<User | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Datarequest])
  @nestAccessControl.UseRoles({
    resource: "Datarequest",
    action: "read",
    possession: "any",
  })
  async datarequestsaskid(
    @graphql.Parent() parent: User,
    @graphql.Args() args: DatarequestFindManyArgs
  ): Promise<Datarequest[]> {
    const results = await this.service.findDatarequestsaskid(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Datarequest])
  @nestAccessControl.UseRoles({
    resource: "Datarequest",
    action: "read",
    possession: "any",
  })
  async datarequestsreceiveid(
    @graphql.Parent() parent: User,
    @graphql.Args() args: DatarequestFindManyArgs
  ): Promise<Datarequest[]> {
    const results = await this.service.findDatarequestsreceiveid(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Datasuggestion])
  @nestAccessControl.UseRoles({
    resource: "Datasuggestion",
    action: "read",
    possession: "any",
  })
  async datasuggestionsreceiveid(
    @graphql.Parent() parent: User,
    @graphql.Args() args: DatasuggestionFindManyArgs
  ): Promise<Datasuggestion[]> {
    const results = await this.service.findDatasuggestionsreceiveid(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Datasuggestion])
  @nestAccessControl.UseRoles({
    resource: "Datasuggestion",
    action: "read",
    possession: "any",
  })
  async datasuggestionssuggestionid(
    @graphql.Parent() parent: User,
    @graphql.Args() args: DatasuggestionFindManyArgs
  ): Promise<Datasuggestion[]> {
    const results = await this.service.findDatasuggestionssuggestionid(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Group])
  @nestAccessControl.UseRoles({
    resource: "Group",
    action: "read",
    possession: "any",
  })
  async groupsownerid(
    @graphql.Parent() parent: User,
    @graphql.Args() args: GroupFindManyArgs
  ): Promise<Group[]> {
    const results = await this.service.findGroupsownerid(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Linksharing])
  @nestAccessControl.UseRoles({
    resource: "Linksharing",
    action: "read",
    possession: "any",
  })
  async linksharings(
    @graphql.Parent() parent: User,
    @graphql.Args() args: LinksharingFindManyArgs
  ): Promise<Linksharing[]> {
    const results = await this.service.findLinksharings(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Membergroup])
  @nestAccessControl.UseRoles({
    resource: "Membergroup",
    action: "read",
    possession: "any",
  })
  async membergroups(
    @graphql.Parent() parent: User,
    @graphql.Args() args: MembergroupFindManyArgs
  ): Promise<Membergroup[]> {
    const results = await this.service.findMembergroups(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Myidentity])
  @nestAccessControl.UseRoles({
    resource: "Myidentity",
    action: "read",
    possession: "any",
  })
  async myidentitiesidentityid(
    @graphql.Parent() parent: User,
    @graphql.Args() args: MyidentityFindManyArgs
  ): Promise<Myidentity[]> {
    const results = await this.service.findMyidentitiesidentityid(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Myidentity])
  @nestAccessControl.UseRoles({
    resource: "Myidentity",
    action: "read",
    possession: "any",
  })
  async myidentitiesmyidentitycontactid(
    @graphql.Parent() parent: User,
    @graphql.Args() args: MyidentityFindManyArgs
  ): Promise<Myidentity[]> {
    const results = await this.service.findMyidentitiesmyidentitycontactid(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Profile])
  @nestAccessControl.UseRoles({
    resource: "Profile",
    action: "read",
    possession: "any",
  })
  async profiles(
    @graphql.Parent() parent: User,
    @graphql.Args() args: ProfileFindManyArgs
  ): Promise<Profile[]> {
    const results = await this.service.findProfiles(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Profileview])
  @nestAccessControl.UseRoles({
    resource: "Profileview",
    action: "read",
    possession: "any",
  })
  async profileviewsidentityid(
    @graphql.Parent() parent: User,
    @graphql.Args() args: ProfileviewFindManyArgs
  ): Promise<Profileview[]> {
    const results = await this.service.findProfileviewsidentityid(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Profileview])
  @nestAccessControl.UseRoles({
    resource: "Profileview",
    action: "read",
    possession: "any",
  })
  async profileviewswatchid(
    @graphql.Parent() parent: User,
    @graphql.Args() args: ProfileviewFindManyArgs
  ): Promise<Profileview[]> {
    const results = await this.service.findProfileviewswatchid(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Enumblockuser, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Enumblockuser",
    action: "read",
    possession: "any",
  })
  async isblocked(
    @graphql.Parent() parent: User
  ): Promise<Enumblockuser | null> {
    const result = await this.service.getIsblocked(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
