/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";

import {
  Prisma,
  User,
  Datarequest,
  Datasuggestion,
  Group,
  Linksharing,
  Membergroup,
  Myidentity,
  Profile,
  Profileview,
  Enumblockuser,
} from "@prisma/client";

import { PasswordService } from "../../auth/password.service";
import { transformStringFieldUpdateInput } from "../../prisma.util";

export class UserServiceBase {
  constructor(
    protected readonly prisma: PrismaService,
    protected readonly passwordService: PasswordService
  ) {}

  async count<T extends Prisma.UserFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.UserFindManyArgs>
  ): Promise<number> {
    return this.prisma.user.count(args);
  }

  async findMany<T extends Prisma.UserFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.UserFindManyArgs>
  ): Promise<User[]> {
    return this.prisma.user.findMany(args);
  }
  async findOne<T extends Prisma.UserFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.UserFindUniqueArgs>
  ): Promise<User | null> {
    return this.prisma.user.findUnique(args);
  }
  async create<T extends Prisma.UserCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.UserCreateArgs>
  ): Promise<User> {
    return this.prisma.user.create<T>({
      ...args,

      data: {
        ...args.data,
        password: await this.passwordService.hash(args.data.password),
      },
    });
  }
  async update<T extends Prisma.UserUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.UserUpdateArgs>
  ): Promise<User> {
    return this.prisma.user.update<T>({
      ...args,

      data: {
        ...args.data,

        password:
          args.data.password &&
          (await transformStringFieldUpdateInput(
            args.data.password,
            (password) => this.passwordService.hash(password)
          )),
      },
    });
  }
  async delete<T extends Prisma.UserDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.UserDeleteArgs>
  ): Promise<User> {
    return this.prisma.user.delete(args);
  }

  async findDatarequestsaskid(
    parentId: string,
    args: Prisma.DatarequestFindManyArgs
  ): Promise<Datarequest[]> {
    return this.prisma.user
      .findUnique({
        where: { id: parentId },
      })
      .datarequestsaskid(args);
  }

  async findDatarequestsreceiveid(
    parentId: string,
    args: Prisma.DatarequestFindManyArgs
  ): Promise<Datarequest[]> {
    return this.prisma.user
      .findUnique({
        where: { id: parentId },
      })
      .datarequestsreceiveid(args);
  }

  async findDatasuggestionsreceiveid(
    parentId: string,
    args: Prisma.DatasuggestionFindManyArgs
  ): Promise<Datasuggestion[]> {
    return this.prisma.user
      .findUnique({
        where: { id: parentId },
      })
      .datasuggestionsreceiveid(args);
  }

  async findDatasuggestionssuggestionid(
    parentId: string,
    args: Prisma.DatasuggestionFindManyArgs
  ): Promise<Datasuggestion[]> {
    return this.prisma.user
      .findUnique({
        where: { id: parentId },
      })
      .datasuggestionssuggestionid(args);
  }

  async findGroupsownerid(
    parentId: string,
    args: Prisma.GroupFindManyArgs
  ): Promise<Group[]> {
    return this.prisma.user
      .findUnique({
        where: { id: parentId },
      })
      .groupsownerid(args);
  }

  async findLinksharings(
    parentId: string,
    args: Prisma.LinksharingFindManyArgs
  ): Promise<Linksharing[]> {
    return this.prisma.user
      .findUnique({
        where: { id: parentId },
      })
      .linksharings(args);
  }

  async findMembergroups(
    parentId: string,
    args: Prisma.MembergroupFindManyArgs
  ): Promise<Membergroup[]> {
    return this.prisma.user
      .findUnique({
        where: { id: parentId },
      })
      .membergroups(args);
  }

  async findMyidentitiesidentityid(
    parentId: string,
    args: Prisma.MyidentityFindManyArgs
  ): Promise<Myidentity[]> {
    return this.prisma.user
      .findUnique({
        where: { id: parentId },
      })
      .myidentitiesidentityid(args);
  }

  async findMyidentitiesmyidentitycontactid(
    parentId: string,
    args: Prisma.MyidentityFindManyArgs
  ): Promise<Myidentity[]> {
    return this.prisma.user
      .findUnique({
        where: { id: parentId },
      })
      .myidentitiesmyidentitycontactid(args);
  }

  async findProfiles(
    parentId: string,
    args: Prisma.ProfileFindManyArgs
  ): Promise<Profile[]> {
    return this.prisma.user
      .findUnique({
        where: { id: parentId },
      })
      .profiles(args);
  }

  async findProfileviewsidentityid(
    parentId: string,
    args: Prisma.ProfileviewFindManyArgs
  ): Promise<Profileview[]> {
    return this.prisma.user
      .findUnique({
        where: { id: parentId },
      })
      .profileviewsidentityid(args);
  }

  async findProfileviewswatchid(
    parentId: string,
    args: Prisma.ProfileviewFindManyArgs
  ): Promise<Profileview[]> {
    return this.prisma.user
      .findUnique({
        where: { id: parentId },
      })
      .profileviewswatchid(args);
  }

  async getIsblocked(parentId: string): Promise<Enumblockuser | null> {
    return this.prisma.user
      .findUnique({
        where: { id: parentId },
      })
      .isblocked();
  }
}
