/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProfileviewService } from "../profileview.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProfileviewCreateInput } from "./ProfileviewCreateInput";
import { ProfileviewWhereInput } from "./ProfileviewWhereInput";
import { ProfileviewWhereUniqueInput } from "./ProfileviewWhereUniqueInput";
import { ProfileviewFindManyArgs } from "./ProfileviewFindManyArgs";
import { ProfileviewUpdateInput } from "./ProfileviewUpdateInput";
import { Profileview } from "./Profileview";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProfileviewControllerBase {
  constructor(
    protected readonly service: ProfileviewService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Profileview",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Profileview })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: ProfileviewCreateInput
  ): Promise<Profileview> {
    return await this.service.create({
      data: {
        ...data,

        identityid: data.identityid
          ? {
              connect: data.identityid,
            }
          : undefined,

        viewcategoryid: data.viewcategoryid
          ? {
              connect: data.viewcategoryid,
            }
          : undefined,

        watchid: data.watchid
          ? {
              connect: data.watchid,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        identityid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        viewcategoryid: {
          select: {
            id: true,
          },
        },

        watchid: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Profileview",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Profileview] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ProfileviewFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Profileview[]> {
    const args = plainToClass(ProfileviewFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,

        identityid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        viewcategoryid: {
          select: {
            id: true,
          },
        },

        watchid: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Profileview",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Profileview })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ProfileviewWhereUniqueInput
  ): Promise<Profileview | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,

        identityid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        viewcategoryid: {
          select: {
            id: true,
          },
        },

        watchid: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Profileview",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Profileview })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ProfileviewWhereUniqueInput,
    @common.Body() data: ProfileviewUpdateInput
  ): Promise<Profileview | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          identityid: data.identityid
            ? {
                connect: data.identityid,
              }
            : undefined,

          viewcategoryid: data.viewcategoryid
            ? {
                connect: data.viewcategoryid,
              }
            : undefined,

          watchid: data.watchid
            ? {
                connect: data.watchid,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          identityid: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          viewcategoryid: {
            select: {
              id: true,
            },
          },

          watchid: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Profileview",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Profileview })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ProfileviewWhereUniqueInput
  ): Promise<Profileview | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,

          identityid: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          viewcategoryid: {
            select: {
              id: true,
            },
          },

          watchid: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
