/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DatasuggestionService } from "../datasuggestion.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DatasuggestionCreateInput } from "./DatasuggestionCreateInput";
import { DatasuggestionWhereInput } from "./DatasuggestionWhereInput";
import { DatasuggestionWhereUniqueInput } from "./DatasuggestionWhereUniqueInput";
import { DatasuggestionFindManyArgs } from "./DatasuggestionFindManyArgs";
import { DatasuggestionUpdateInput } from "./DatasuggestionUpdateInput";
import { Datasuggestion } from "./Datasuggestion";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DatasuggestionControllerBase {
  constructor(
    protected readonly service: DatasuggestionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Datasuggestion",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Datasuggestion })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: DatasuggestionCreateInput
  ): Promise<Datasuggestion> {
    return await this.service.create({
      data: {
        ...data,

        receiveid: data.receiveid
          ? {
              connect: data.receiveid,
            }
          : undefined,

        suggestioncategoryid: data.suggestioncategoryid
          ? {
              connect: data.suggestioncategoryid,
            }
          : undefined,

        suggestionid: data.suggestionid
          ? {
              connect: data.suggestionid,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        isactivesuggestion: true,

        receiveid: {
          select: {
            id: true,
          },
        },

        status: true,

        suggestioncategoryid: {
          select: {
            id: true,
          },
        },

        suggestionid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Datasuggestion",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Datasuggestion] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(DatasuggestionFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Datasuggestion[]> {
    const args = plainToClass(DatasuggestionFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        isactivesuggestion: true,

        receiveid: {
          select: {
            id: true,
          },
        },

        status: true,

        suggestioncategoryid: {
          select: {
            id: true,
          },
        },

        suggestionid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Datasuggestion",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Datasuggestion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: DatasuggestionWhereUniqueInput
  ): Promise<Datasuggestion | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        isactivesuggestion: true,

        receiveid: {
          select: {
            id: true,
          },
        },

        status: true,

        suggestioncategoryid: {
          select: {
            id: true,
          },
        },

        suggestionid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Datasuggestion",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Datasuggestion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: DatasuggestionWhereUniqueInput,
    @common.Body() data: DatasuggestionUpdateInput
  ): Promise<Datasuggestion | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          receiveid: data.receiveid
            ? {
                connect: data.receiveid,
              }
            : undefined,

          suggestioncategoryid: data.suggestioncategoryid
            ? {
                connect: data.suggestioncategoryid,
              }
            : undefined,

          suggestionid: data.suggestionid
            ? {
                connect: data.suggestionid,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          isactivesuggestion: true,

          receiveid: {
            select: {
              id: true,
            },
          },

          status: true,

          suggestioncategoryid: {
            select: {
              id: true,
            },
          },

          suggestionid: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Datasuggestion",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Datasuggestion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: DatasuggestionWhereUniqueInput
  ): Promise<Datasuggestion | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          isactivesuggestion: true,

          receiveid: {
            select: {
              id: true,
            },
          },

          status: true,

          suggestioncategoryid: {
            select: {
              id: true,
            },
          },

          suggestionid: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
