/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { FileprofileCreateNestedManyWithoutProfilesInput } from "./FileprofileCreateNestedManyWithoutProfilesInput";
import { Type } from "class-transformer";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { LinkprofileCreateNestedManyWithoutProfilesInput } from "./LinkprofileCreateNestedManyWithoutProfilesInput";
@InputType()
class ProfileCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  content?: string | null;

  @ApiProperty({
    required: false,
    type: () => FileprofileCreateNestedManyWithoutProfilesInput,
  })
  @ValidateNested()
  @Type(() => FileprofileCreateNestedManyWithoutProfilesInput)
  @IsOptional()
  @Field(() => FileprofileCreateNestedManyWithoutProfilesInput, {
    nullable: true,
  })
  fileprofiles?: FileprofileCreateNestedManyWithoutProfilesInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  identityid?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => LinkprofileCreateNestedManyWithoutProfilesInput,
  })
  @ValidateNested()
  @Type(() => LinkprofileCreateNestedManyWithoutProfilesInput)
  @IsOptional()
  @Field(() => LinkprofileCreateNestedManyWithoutProfilesInput, {
    nullable: true,
  })
  linkprofiles?: LinkprofileCreateNestedManyWithoutProfilesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}
export { ProfileCreateInput };
