/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProfileService } from "../profile.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProfileCreateInput } from "./ProfileCreateInput";
import { ProfileWhereInput } from "./ProfileWhereInput";
import { ProfileWhereUniqueInput } from "./ProfileWhereUniqueInput";
import { ProfileFindManyArgs } from "./ProfileFindManyArgs";
import { ProfileUpdateInput } from "./ProfileUpdateInput";
import { Profile } from "./Profile";
import { FileprofileFindManyArgs } from "../../fileprofile/base/FileprofileFindManyArgs";
import { Fileprofile } from "../../fileprofile/base/Fileprofile";
import { FileprofileWhereUniqueInput } from "../../fileprofile/base/FileprofileWhereUniqueInput";
import { LinkprofileFindManyArgs } from "../../linkprofile/base/LinkprofileFindManyArgs";
import { Linkprofile } from "../../linkprofile/base/Linkprofile";
import { LinkprofileWhereUniqueInput } from "../../linkprofile/base/LinkprofileWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProfileControllerBase {
  constructor(
    protected readonly service: ProfileService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Profile",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Profile })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: ProfileCreateInput): Promise<Profile> {
    return await this.service.create({
      data: {
        ...data,

        identityid: data.identityid
          ? {
              connect: data.identityid,
            }
          : undefined,
      },
      select: {
        content: true,
        createdAt: true,
        id: true,

        identityid: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Profile",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Profile] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(ProfileFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Profile[]> {
    const args = plainToClass(ProfileFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        content: true,
        createdAt: true,
        id: true,

        identityid: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Profile",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Profile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: ProfileWhereUniqueInput
  ): Promise<Profile | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        content: true,
        createdAt: true,
        id: true,

        identityid: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Profile",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Profile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: ProfileWhereUniqueInput,
    @common.Body() data: ProfileUpdateInput
  ): Promise<Profile | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          identityid: data.identityid
            ? {
                connect: data.identityid,
              }
            : undefined,
        },
        select: {
          content: true,
          createdAt: true,
          id: true,

          identityid: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Profile",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Profile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: ProfileWhereUniqueInput
  ): Promise<Profile | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          content: true,
          createdAt: true,
          id: true,

          identityid: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Fileprofile",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/fileprofiles")
  @ApiNestedQuery(FileprofileFindManyArgs)
  async findManyFileprofiles(
    @common.Req() request: Request,
    @common.Param() params: ProfileWhereUniqueInput
  ): Promise<Fileprofile[]> {
    const query = plainToClass(FileprofileFindManyArgs, request.query);
    const results = await this.service.findFileprofiles(params.id, {
      ...query,
      select: {
        categoryid: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        file: true,
        id: true,
        ispublic: true,

        profileid: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Profile",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/fileprofiles")
  async connectFileprofiles(
    @common.Param() params: ProfileWhereUniqueInput,
    @common.Body() body: FileprofileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fileprofiles: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Profile",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/fileprofiles")
  async updateFileprofiles(
    @common.Param() params: ProfileWhereUniqueInput,
    @common.Body() body: FileprofileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fileprofiles: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Profile",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/fileprofiles")
  async disconnectFileprofiles(
    @common.Param() params: ProfileWhereUniqueInput,
    @common.Body() body: FileprofileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      fileprofiles: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Linkprofile",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/linkprofiles")
  @ApiNestedQuery(LinkprofileFindManyArgs)
  async findManyLinkprofiles(
    @common.Req() request: Request,
    @common.Param() params: ProfileWhereUniqueInput
  ): Promise<Linkprofile[]> {
    const query = plainToClass(LinkprofileFindManyArgs, request.query);
    const results = await this.service.findLinkprofiles(params.id, {
      ...query,
      select: {
        categoryid: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        ispublic: true,

        profileid: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
        url: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Profile",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/linkprofiles")
  async connectLinkprofiles(
    @common.Param() params: ProfileWhereUniqueInput,
    @common.Body() body: LinkprofileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      linkprofiles: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Profile",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/linkprofiles")
  async updateLinkprofiles(
    @common.Param() params: ProfileWhereUniqueInput,
    @common.Body() body: LinkprofileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      linkprofiles: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Profile",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/linkprofiles")
  async disconnectLinkprofiles(
    @common.Param() params: ProfileWhereUniqueInput,
    @common.Body() body: LinkprofileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      linkprofiles: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
