/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { FileprofileUpdateManyWithoutProfilesInput } from "./FileprofileUpdateManyWithoutProfilesInput";
import { Type } from "class-transformer";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { LinkprofileUpdateManyWithoutProfilesInput } from "./LinkprofileUpdateManyWithoutProfilesInput";
@InputType()
class ProfileUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  content?: string | null;

  @ApiProperty({
    required: false,
    type: () => FileprofileUpdateManyWithoutProfilesInput,
  })
  @ValidateNested()
  @Type(() => FileprofileUpdateManyWithoutProfilesInput)
  @IsOptional()
  @Field(() => FileprofileUpdateManyWithoutProfilesInput, {
    nullable: true,
  })
  fileprofiles?: FileprofileUpdateManyWithoutProfilesInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  identityid?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => LinkprofileUpdateManyWithoutProfilesInput,
  })
  @ValidateNested()
  @Type(() => LinkprofileUpdateManyWithoutProfilesInput)
  @IsOptional()
  @Field(() => LinkprofileUpdateManyWithoutProfilesInput, {
    nullable: true,
  })
  linkprofiles?: LinkprofileUpdateManyWithoutProfilesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}
export { ProfileUpdateInput };
