/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { LinkcategoryService } from "../linkcategory.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LinkcategoryCreateInput } from "./LinkcategoryCreateInput";
import { LinkcategoryWhereInput } from "./LinkcategoryWhereInput";
import { LinkcategoryWhereUniqueInput } from "./LinkcategoryWhereUniqueInput";
import { LinkcategoryFindManyArgs } from "./LinkcategoryFindManyArgs";
import { LinkcategoryUpdateInput } from "./LinkcategoryUpdateInput";
import { Linkcategory } from "./Linkcategory";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LinkcategoryControllerBase {
  constructor(
    protected readonly service: LinkcategoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Linkcategory",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Linkcategory })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: LinkcategoryCreateInput
  ): Promise<Linkcategory> {
    return await this.service.create({
      data: {
        ...data,

        categoryid: data.categoryid
          ? {
              connect: data.categoryid,
            }
          : undefined,

        linkid: data.linkid
          ? {
              connect: data.linkid,
            }
          : undefined,
      },
      select: {
        categoryid: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        linkid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Linkcategory",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Linkcategory] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(LinkcategoryFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Linkcategory[]> {
    const args = plainToClass(LinkcategoryFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        categoryid: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        linkid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Linkcategory",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Linkcategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: LinkcategoryWhereUniqueInput
  ): Promise<Linkcategory | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        categoryid: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        linkid: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Linkcategory",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Linkcategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: LinkcategoryWhereUniqueInput,
    @common.Body() data: LinkcategoryUpdateInput
  ): Promise<Linkcategory | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          categoryid: data.categoryid
            ? {
                connect: data.categoryid,
              }
            : undefined,

          linkid: data.linkid
            ? {
                connect: data.linkid,
              }
            : undefined,
        },
        select: {
          categoryid: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,

          linkid: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Linkcategory",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Linkcategory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: LinkcategoryWhereUniqueInput
  ): Promise<Linkcategory | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          categoryid: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,

          linkid: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
