/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { LinkprofileService } from "../linkprofile.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LinkprofileCreateInput } from "./LinkprofileCreateInput";
import { LinkprofileWhereInput } from "./LinkprofileWhereInput";
import { LinkprofileWhereUniqueInput } from "./LinkprofileWhereUniqueInput";
import { LinkprofileFindManyArgs } from "./LinkprofileFindManyArgs";
import { LinkprofileUpdateInput } from "./LinkprofileUpdateInput";
import { Linkprofile } from "./Linkprofile";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LinkprofileControllerBase {
  constructor(
    protected readonly service: LinkprofileService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Linkprofile",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Linkprofile })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: LinkprofileCreateInput
  ): Promise<Linkprofile> {
    return await this.service.create({
      data: {
        ...data,

        categoryid: data.categoryid
          ? {
              connect: data.categoryid,
            }
          : undefined,

        profileid: data.profileid
          ? {
              connect: data.profileid,
            }
          : undefined,
      },
      select: {
        categoryid: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        ispublic: true,

        profileid: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Linkprofile",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Linkprofile] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(LinkprofileFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Linkprofile[]> {
    const args = plainToClass(LinkprofileFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        categoryid: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        ispublic: true,

        profileid: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
        url: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Linkprofile",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Linkprofile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: LinkprofileWhereUniqueInput
  ): Promise<Linkprofile | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        categoryid: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        ispublic: true,

        profileid: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
        url: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Linkprofile",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Linkprofile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: LinkprofileWhereUniqueInput,
    @common.Body() data: LinkprofileUpdateInput
  ): Promise<Linkprofile | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          categoryid: data.categoryid
            ? {
                connect: data.categoryid,
              }
            : undefined,

          profileid: data.profileid
            ? {
                connect: data.profileid,
              }
            : undefined,
        },
        select: {
          categoryid: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          ispublic: true,

          profileid: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Linkprofile",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Linkprofile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: LinkprofileWhereUniqueInput
  ): Promise<Linkprofile | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          categoryid: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          ispublic: true,

          profileid: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,
          url: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
