/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FileprofileService } from "../fileprofile.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FileprofileCreateInput } from "./FileprofileCreateInput";
import { FileprofileWhereInput } from "./FileprofileWhereInput";
import { FileprofileWhereUniqueInput } from "./FileprofileWhereUniqueInput";
import { FileprofileFindManyArgs } from "./FileprofileFindManyArgs";
import { FileprofileUpdateInput } from "./FileprofileUpdateInput";
import { Fileprofile } from "./Fileprofile";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FileprofileControllerBase {
  constructor(
    protected readonly service: FileprofileService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Fileprofile",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Fileprofile })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: FileprofileCreateInput
  ): Promise<Fileprofile> {
    return await this.service.create({
      data: {
        ...data,

        categoryid: data.categoryid
          ? {
              connect: data.categoryid,
            }
          : undefined,

        profileid: data.profileid
          ? {
              connect: data.profileid,
            }
          : undefined,
      },
      select: {
        categoryid: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        file: true,
        id: true,
        ispublic: true,

        profileid: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Fileprofile",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Fileprofile] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(FileprofileFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Fileprofile[]> {
    const args = plainToClass(FileprofileFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        categoryid: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        file: true,
        id: true,
        ispublic: true,

        profileid: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Fileprofile",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Fileprofile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: FileprofileWhereUniqueInput
  ): Promise<Fileprofile | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        categoryid: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        file: true,
        id: true,
        ispublic: true,

        profileid: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Fileprofile",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Fileprofile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: FileprofileWhereUniqueInput,
    @common.Body() data: FileprofileUpdateInput
  ): Promise<Fileprofile | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          categoryid: data.categoryid
            ? {
                connect: data.categoryid,
              }
            : undefined,

          profileid: data.profileid
            ? {
                connect: data.profileid,
              }
            : undefined,
        },
        select: {
          categoryid: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          file: true,
          id: true,
          ispublic: true,

          profileid: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Fileprofile",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Fileprofile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: FileprofileWhereUniqueInput
  ): Promise<Fileprofile | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          categoryid: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          file: true,
          id: true,
          ispublic: true,

          profileid: {
            select: {
              id: true,
            },
          },

          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
